### ISSUE TITLE
build.gradle

### ISSUE THREAD

**Issue by BleachDev** [dewysoftwareleaks/Ruhama#2]
shadowjar isn't needed for the build.gradle file if you configure the mixins correctly, also, mixin 0.8 is pretty incompatible with mixin 0.7 projects so you shouldn't use it, but i barely have any mixins so it should be fine

[here](https://hastebin.com/anazinecux.java) is the original build.gradle file for reference

**Comment by BleachDev** [comment]
shadowing all the mixin files adds like 2mb of extra junk in the jar, it should only be like 200kb when its compiled

**Comment by BitBuf** [comment]
Well, the shadow jar isn't your only option :p

But ye, I've downgraded the Mixins to 0.7.11 and optimised the shadow jar, removing stuff like Apache Commons that's in there for some reason. Thanks for the heads up!
