### ISSUE TITLE
no click gui bind

### ISSUE THREAD

**Issue by blixten808** [dewysoftwareleaks/Ruhama#3]
Hi
My issue is theres no click gui bind.
I would really appreciate if you would add a Click gui bind!

**Comment by BitBuf** [comment]
This isn't in my jurisdiction; I won't be modifying any part of this codebase by fixing anything or adding new features or modules. To bring up the clickgui, you must enter the controls menu in the vanilla Minecraft options screen.

**Comment by 5HT2** [comment]
it's in the controls options lmao

**Comment by 5HT2** [comment]
it's not dewys fault that ruhama is a pile of shit, he didn't make it

**Comment by blixten808** [comment]
oh ok ty

**Comment by blixten808** [comment]
Im stupid and shit and i cant find it in controls in settings

**Comment by 5HT2** [comment]
have you never played minecraft before?

**Comment by blixten808** [comment]
ofc but im stupid and i try finding it in controls in settings and i cannot find it
