### ISSUE TITLE
Alot Of Crashes 

### ISSUE THREAD

**Issue by Radioplus** [dewysoftwareleaks/Ruhama#6]
I cant open the client without it crashing or not opening at all. what i use is Ruhama And Sodium

**Comment by KMatias123** [comment]
its for 1.12.2 forge

**Comment by Radioplus** [comment]
> its for 1.12.2 forge

this is a fucking troll retard

**Comment by KMatias123** [comment]
best troll

**Comment by Radioplus** [comment]
> best troll

didn't ask
